name: Weekly Line Notify

on:
  schedule:
    # cronスケジュールの設定
    # UTC時間で設定。9:00 JSTは0:00 UTC
    - cron: '0 0 * * 5'  # 毎週金曜日の9:00 JST
    - cron: '0 0 * * 2'  # 毎週火曜日の9:00 JST
    - cron: '0 0 * * 3'  # 毎週水曜日の9:00 JST
    - cron: '0 0 * * 6'  # 毎週土曜日の9:00 JST
    - cron: '0 0 1-7,15-21 * 4'  # 毎月第1と第3木曜日の9:00 JST

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests schedule

      - name: Send Line Notify message
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: |
          python -c "
import requests
from datetime import datetime

# LINE Notifyにメッセージを送信する関数
def send_line_notify(message):
    url = 'https://notify-api.line.me/api/notify'
    headers = {
        'Authorization': f'Bearer {os.getenv('LINE_NOTIFY_TOKEN')}'
    }
    data = {'message': message}
    requests.post(url, headers=headers, data=data)

# 曜日ごとのメッセージを送信
today = datetime.today()
weekday = today.weekday()

if weekday == 4:  # 金曜日
    send_line_notify('資源プラスチックの回収日')
elif weekday == 1:  # 火曜日
    send_line_notify('資源ゴミの回収日')
elif weekday == 2 or weekday == 5:  # 水曜日または土曜日
    send_line_notify('燃えるゴミの回収日')
elif weekday == 3:  # 木曜日
    if today.day in range(1, 8) or 15 <= today.day <= 21:  # 第1 or 第3木曜日
        send_line_notify('燃えないゴミの回収日')
"
